version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bookhub-postgres
    environment:
      POSTGRES_DB: bookhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/changelog:/docker-entrypoint-initdb.d
    networks:
      - bookhub-network

  mongodb:
    image: mongo:7.0
    container_name: bookhub-mongodb
    environment:
      MONGO_INITDB_DATABASE: bookhub
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bookhub-network

  redis:
    image: redis:7.2-alpine
    container_name: bookhub-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bookhub-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data
    ports:
      - "9200:9200"
    networks:
      - bookhub-network

  app:
    build: .
    container_name: bookhub-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookhub
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/bookhub
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_ELASTICSEARCH_HOST: elasticsearch
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
      - redis
      - elasticsearch
    networks:
      - bookhub-network

volumes:
  postgres_data:
  mongodb_data:
  redis_data:

networks:
  bookhub-network:
    driver: bridge